import json, sys
sys.stdout.reconfigure(encoding='utf-8')

with open('analysis.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

def make_code(src):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': [src]}

def make_md(src):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': [src]}

new_cells = []

# ── Section 17 header ─────────────────────────────────────────────────────────
new_cells.append(make_md(
    "## Section 17: Intraday Retracement — Better Entry Opportunities After 10am?\n"
    "\n"
    "After the 10am signal is confirmed (Strong drift + non-Q4 + not Thu), 84% of days are already\n"
    "deep in-the-money on the binary (~$75). But does price ever pull back during the rest of\n"
    "the day — giving a chance to enter a cheaper binary (or a better-priced futures position)?\n"
    "\n"
    "**Key questions:**\n"
    "1. How often does price retrace against the trade direction after 10am?\n"
    "2. How deep do those retracements go (as % of the open-to-contract gap)?\n"
    "3. When do they occur (hour of day)?\n"
    "4. On days where price crosses back past the contract (binary goes back to near-money), does the trade still win?"
))

# ── Section 17a ───────────────────────────────────────────────────────────────
s17a = (
    "# Section 17a: Intraday retracement depth on Strong + non-Q4 + not-Thu days\n"
    "# Requires: df (all bars with time_parsed), early, wide_rev13, is_strong/is_q4/is_thursday\n"
    "\n"
    "import datetime\n"
    "\n"
    "# Get the 39 high-probability dates\n"
    "best_mask = wide_rev13['is_strong'] & ~wide_rev13['is_q4'] & ~wide_rev13['is_thursday']\n"
    "best_days = wide_rev13[best_mask][[\n"
    "    'date', 'initial_direction', 'contract_location', 'market_open_09:30',\n"
    "    'won', 'diff_open_conLoc', 'drift_magnitude', 'progress_ratio'\n"
    "]].copy()\n"
    "best_dates = set(best_days['date'])\n"
    "\n"
    "cut_10am = datetime.time(10, 0, 0)\n"
    "\n"
    "# 10am price snapshot (last bar at or before 10:00)\n"
    "snap_1000 = (\n"
    "    early[early['time_parsed'] <= cut_10am]\n"
    "    .groupby('date')['candle_close_price'].last()\n"
    "    .rename('price_1000').reset_index()\n"
    ")\n"
    "\n"
    "# All bars after 10am on those dates\n"
    "after10 = df[df['date'].isin(best_dates) & (df['time_parsed'] > cut_10am)].copy()\n"
    "after10 = after10.merge(best_days, on='date', how='inner')\n"
    "after10 = after10.merge(snap_1000, on='date', how='left')\n"
    "\n"
    "# Per-day retrace metrics\n"
    "def retrace_metrics(group):\n"
    "    direction = group['initial_direction'].iloc[0]\n"
    "    contract  = group['contract_location'].iloc[0]\n"
    "    gap       = group['diff_open_conLoc'].iloc[0]\n"
    "    won       = group['won'].iloc[0]\n"
    "    p10am     = group['price_1000'].iloc[0]\n"
    "\n"
    "    if pd.isna(p10am) or gap == 0:\n"
    "        return pd.Series({'won': won, 'retrace_pts': np.nan,\n"
    "                          'retrace_pct_of_gap': np.nan, 'crossed_contract': False, 'worst_hour': np.nan})\n"
    "\n"
    "    if direction == 'above':\n"
    "        # Trade: SELL (expecting fall). Retrace = price bouncing back UP.\n"
    "        extreme      = group['candle_high_price'].max()\n"
    "        retrace_pts  = max(extreme - p10am, 0)\n"
    "        crossed      = bool(extreme > contract)   # went back above contract\n"
    "        idx_worst    = group['candle_high_price'].idxmax()\n"
    "    else:\n"
    "        # Trade: BUY (expecting rise). Retrace = price pulling back DOWN.\n"
    "        extreme      = group['candle_low_price'].min()\n"
    "        retrace_pts  = max(p10am - extreme, 0)\n"
    "        crossed      = bool(extreme < contract)   # went back below contract\n"
    "        idx_worst    = group['candle_low_price'].idxmin()\n"
    "\n"
    "    worst_hour = group.loc[idx_worst, 'time_parsed'].hour\n"
    "\n"
    "    return pd.Series({\n"
    "        'won':                won,\n"
    "        'retrace_pts':        retrace_pts,\n"
    "        'retrace_pct_of_gap': retrace_pts / gap,\n"
    "        'crossed_contract':   crossed,\n"
    "        'worst_hour':         worst_hour,\n"
    "    })\n"
    "\n"
    "retrace_df = after10.groupby('date').apply(retrace_metrics, include_groups=False).reset_index()\n"
    "\n"
    "n_total   = len(retrace_df)\n"
    "n_crossed = int(retrace_df['crossed_contract'].sum())\n"
    "\n"
    "print(f'High-probability days analyzed: {n_total}  (Strong drift + non-Q4 + not Thursday)')\n"
    "print()\n"
    "print(f'Days with ANY retrace past contract location: {n_crossed} / {n_total} ({n_crossed/n_total:.1%})')\n"
    "print()\n"
    "\n"
    "crossed_wr   = retrace_df.loc[ retrace_df['crossed_contract'], 'won'].mean()\n"
    "not_cross_wr = retrace_df.loc[~retrace_df['crossed_contract'], 'won'].mean()\n"
    "print(f'Win rate -- no contract crossback  : {not_cross_wr:.1%}  (N={int((~retrace_df[\"crossed_contract\"]).sum())})')\n"
    "print(f'Win rate -- price crossed contract : {crossed_wr:.1%}  (N={n_crossed})')\n"
    "print()\n"
    "\n"
    "retrace_df['retrace_bin'] = pd.cut(\n"
    "    retrace_df['retrace_pct_of_gap'],\n"
    "    bins=[-np.inf, 0.25, 0.50, 1.0, 1.5, np.inf],\n"
    "    labels=['<25% back', '25-50% back', '50-100% back', '100-150% (past contract)', '>150% past']\n"
    ")\n"
    "depth_tbl = retrace_df.groupby('retrace_bin', observed=True).agg(\n"
    "    n=('won', 'count'), win_rate=('won', 'mean')\n"
    ").round(3)\n"
    "print('Retrace depth (as % of open to contract gap):')\n"
    "print(depth_tbl.to_string())\n"
    "print()\n"
    "print(f'Median retrace : {retrace_df[\"retrace_pts\"].median():.1f} pts  ({retrace_df[\"retrace_pct_of_gap\"].median():.1%} of gap)')\n"
    "print(f'Mean retrace   : {retrace_df[\"retrace_pts\"].mean():.1f} pts  ({retrace_df[\"retrace_pct_of_gap\"].mean():.1%} of gap)')\n"
)
new_cells.append(make_code(s17a))

# ── Section 17b ───────────────────────────────────────────────────────────────
s17b = (
    "# Section 17b: When do pullbacks peak? Chart.\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "\n"
    "# Left: retrace depth histogram\n"
    "axes[0].hist(retrace_df['retrace_pct_of_gap'].dropna() * 100, bins=15,\n"
    "             color='#3498db', edgecolor='white', alpha=0.85)\n"
    "axes[0].axvline(100, color='red', linestyle='--', linewidth=1.5, label='Contract crossback (100%)')\n"
    "axes[0].set_xlabel('Retrace depth (% of open to contract gap)')\n"
    "axes[0].set_ylabel('Days')\n"
    "axes[0].set_title('Intraday Retrace Depth Distribution\\n(Strong + non-Q4 + not Thu, N=39)')\n"
    "axes[0].legend()\n"
    "\n"
    "# Right: hour of worst retrace\n"
    "hour_counts = retrace_df['worst_hour'].value_counts().sort_index()\n"
    "axes[1].bar(hour_counts.index.astype(int), hour_counts.values, color='#e67e22', edgecolor='white')\n"
    "axes[1].set_xlabel('Hour (ET) when worst retrace occurred')\n"
    "axes[1].set_ylabel('Days')\n"
    "axes[1].set_title('When Does the Worst Pullback Peak?\\n(Strong + non-Q4 + not Thu days)')\n"
    "axes[1].set_xticks(range(10, 17))\n"
    "axes[1].set_xticklabels([f'{h}:00' for h in range(10, 17)])\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "# Crossback days detail\n"
    "crossed_df = retrace_df[retrace_df['crossed_contract']]\n"
    "if len(crossed_df) > 0:\n"
    "    print(f'Hours when contract crossback occurred ({n_crossed} days):')\n"
    "    print(crossed_df['worst_hour'].value_counts().sort_index().to_string())\n"
    "    print()\n"
    "    wins_x = int(crossed_df['won'].sum())\n"
    "    print(f'Crossback days: {wins_x} wins, {n_crossed - wins_x} losses  (win rate: {crossed_df[\"won\"].mean():.1%})')\n"
)
new_cells.append(make_code(s17b))

new_cells.append(make_md(
    "*Interpretation:*\n"
    "\n"
    "**What this tells you for futures execution:**\n"
    "- Retraces that stay shallow (<50% of gap): entering on the pullback is risky -- price may not give you a better entry level.\n"
    "- Retraces that cross past the contract: this is a meaningful pullback. For binaries, the price drops sharply. For futures, you get a second chance to enter in the direction of the original trade at a more favorable price.\n"
    "- The hour distribution tells you the typical retracement window. Most S&P mean-reversion setups see the strongest counter-move in the first 1-2 hours after the initial signal.\n"
    "- **Key insight for ES/MES:** If most retraces happen 10am-12pm, a limit order placed 30-50% of the gap back from the 10am price would get filled on most crossback days while still trading in the correct direction."
))

# ── Section 18 header ─────────────────────────────────────────────────────────
new_cells.append(make_md(
    "---\n"
    "## Section 18: Pre-Market Predictability\n"
    "\n"
    "The 10am signal (Wide open + Strong drift reversal) is confirmed only *after* the first 30 minutes.\n"
    "But some inputs are knowable before the open:\n"
    "- **Calendar:** Q4 and Thursday are known in advance (negative filters)\n"
    "- **VIX:** prior close is available pre-market -- higher VIX predicts wider expected range\n"
    "\n"
    "**Key question:** Given only pre-market information, how much can you raise the probability of catching a high-edge day?"
))

# ── Section 18a ───────────────────────────────────────────────────────────────
s18a = (
    "# Section 18a: VIX as predictor of Wide + Reversal + Strong days\n"
    "# Requires: dm (has range_pct, vix_close, vix_category, vix_favorable), wide_rev13\n"
    "\n"
    "import scipy.stats as stats_mod\n"
    "\n"
    "# Flag each day in dm by signal type\n"
    "strong_dates   = set(wide_rev13.loc[wide_rev13['is_strong'], 'date'])\n"
    "best_sig_dates = set(wide_rev13.loc[\n"
    "    wide_rev13['is_strong'] & ~wide_rev13['is_q4'] & ~wide_rev13['is_thursday'], 'date'\n"
    "])\n"
    "wide_rev_dates = set(wide_rev13['date'])\n"
    "\n"
    "dm['is_wide_rev']   = dm['date'].isin(wide_rev_dates)\n"
    "dm['is_strong_wr']  = dm['date'].isin(strong_dates)\n"
    "dm['is_best_signal']= dm['date'].isin(best_sig_dates)\n"
    "\n"
    "# Pearson correlation: VIX vs first-30-min range\n"
    "dm_valid = dm.dropna(subset=['vix_close', 'range_pct'])\n"
    "r_vix, p_vix = stats_mod.pearsonr(dm_valid['vix_close'], dm_valid['range_pct'])\n"
    "print(f'Pearson r -- VIX close (prior day) vs first-30-min range: {r_vix:.3f}  (p={p_vix:.4f})')\n"
    "print()\n"
    "\n"
    "# By VIX category: mean range and signal rates\n"
    "vix_cat_order = ['Low', 'Moderate', 'Elevated', 'High']\n"
    "vix_stats = (\n"
    "    dm.groupby('vix_category', observed=True)\n"
    "    .agg(\n"
    "        n              = ('range_pct',       'count'),\n"
    "        mean_range     = ('range_pct',       'mean'),\n"
    "        pct_wide_rev   = ('is_wide_rev',     'mean'),\n"
    "        pct_strong_wr  = ('is_strong_wr',    'mean'),\n"
    "        pct_best_sig   = ('is_best_signal',  'mean'),\n"
    "    )\n"
    "    .reindex(vix_cat_order)\n"
    ")\n"
    "print('VIX category -> signal frequency:')\n"
    "print(vix_stats[['n','mean_range','pct_wide_rev','pct_strong_wr','pct_best_sig']]\n"
    "      .rename(columns={\n"
    "          'mean_range':   'Mean 30m range%',\n"
    "          'pct_wide_rev': '% Wide+Rev',\n"
    "          'pct_strong_wr':'% Strong+W+R',\n"
    "          'pct_best_sig': '% Best signal',\n"
    "      }).round(3).to_string())\n"
    "print()\n"
    "print('Best signal = Strong drift + non-Q4 + not Thursday')\n"
    "print(f'Baseline best-signal rate (all days): {dm[\"is_best_signal\"].mean():.1%}')\n"
)
new_cells.append(make_code(s18a))

# ── Section 18b ───────────────────────────────────────────────────────────────
s18b = (
    "# Section 18b: Calendar gate + VIX -- combined pre-market probability\n"
    "\n"
    "dm['date_parsed']  = pd.to_datetime(dm['date'])\n"
    "dm['month_num_dm'] = dm['date_parsed'].dt.month\n"
    "dm['dow_dm']       = dm['date_parsed'].dt.day_name()\n"
    "dm['is_q4_dm']     = dm['month_num_dm'].isin([10, 11, 12])\n"
    "dm['is_thu_dm']    = dm['dow_dm'] == 'Thursday'\n"
    "dm['passes_cal']   = ~dm['is_q4_dm'] & ~dm['is_thu_dm']\n"
    "\n"
    "# Signal rate by (calendar pass) x (VIX category)\n"
    "vix_cat_order = ['Low', 'Moderate', 'Elevated', 'High']\n"
    "rows = []\n"
    "for cal_ok in [False, True]:\n"
    "    subset = dm[dm['passes_cal'] == cal_ok]\n"
    "    label  = 'Non-Q4, Non-Thu' if cal_ok else 'Q4 or Thursday'\n"
    "    for vix_cat in vix_cat_order:\n"
    "        sub2 = subset[subset['vix_category'] == vix_cat]\n"
    "        if len(sub2) == 0:\n"
    "            continue\n"
    "        rows.append({\n"
    "            'Calendar':    label,\n"
    "            'VIX':         vix_cat,\n"
    "            'N':           len(sub2),\n"
    "            'Signal rate': sub2['is_best_signal'].mean(),\n"
    "        })\n"
    "\n"
    "prob_tbl = pd.DataFrame(rows)\n"
    "prob_tbl['Signal rate fmt'] = prob_tbl['Signal rate'].map(lambda x: f'{x:.1%}')\n"
    "print('Pre-market probability of best-signal day (Strong drift + non-Q4 + not Thu):')\n"
    "print(prob_tbl[['Calendar','VIX','N','Signal rate fmt']]\n"
    "      .rename(columns={'Signal rate fmt':'Signal rate'})\n"
    "      .to_string(index=False))\n"
    "print()\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "\n"
    "# Left: VIX vs 30-min range box plot\n"
    "dm_vix = dm[dm['vix_category'].isin(vix_cat_order)]\n"
    "groups = [dm_vix.loc[dm_vix['vix_category'] == v, 'range_pct'].dropna() for v in vix_cat_order]\n"
    "axes[0].boxplot(groups, labels=vix_cat_order, patch_artist=True,\n"
    "               boxprops=dict(facecolor='#3498db', alpha=0.6))\n"
    "axes[0].set_xlabel('VIX Category (prior close)')\n"
    "axes[0].set_ylabel('First-30-min range (% of open)')\n"
    "axes[0].set_title(f'VIX Predicts Morning Volatility\\n(r={r_vix:.3f} with VIX level, p={p_vix:.4f})')\n"
    "\n"
    "# Right: signal rate by VIX on calendar-passing days\n"
    "cal_dm    = dm[dm['passes_cal']]\n"
    "cal_vix   = (\n"
    "    cal_dm.groupby('vix_category', observed=True)['is_best_signal']\n"
    "    .agg(['mean', 'count'])\n"
    "    .reindex(vix_cat_order)\n"
    ")\n"
    "baseline  = dm['is_best_signal'].mean()\n"
    "bars = axes[1].bar(cal_vix.index, cal_vix['mean'],\n"
    "                   color=['#2ecc71' if v > baseline else '#e74c3c' for v in cal_vix['mean']])\n"
    "axes[1].axhline(baseline, color='navy', linestyle='--', linewidth=1.2,\n"
    "                label=f'Baseline all days ({baseline:.1%})')\n"
    "axes[1].set_xlabel('VIX Category (non-Q4, non-Thu days only)')\n"
    "axes[1].set_ylabel('Probability of best-signal day')\n"
    "axes[1].set_title('Pre-Market Signal Probability by VIX\\n(calendar gate already applied)')\n"
    "axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))\n"
    "axes[1].legend()\n"
    "for bar, (_, row) in zip(bars, cal_vix.iterrows()):\n"
    "    if not pd.isna(row['mean']):\n"
    "        axes[1].text(bar.get_x() + bar.get_width()/2, row['mean'] + 0.002,\n"
    "                     f'{row[\"mean\"]:.1%}\\n(N={int(row[\"count\"])})',\n"
    "                     ha='center', va='bottom', fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
)
new_cells.append(make_code(s18b))

new_cells.append(make_md(
    "*Interpretation:*\n"
    "\n"
    "**Pre-market decision checklist (what you can know before 9:30am):**\n"
    "\n"
    "| Check | Question | If yes... |\n"
    "|---|---|---|\n"
    "| 1. Calendar | Is today non-Q4 (Jan-Sep) AND not Thursday? | Continue |\n"
    "| 2. VIX | Is VIX (prior close) in Moderate-Elevated range (15-30)? | Higher probability of Wide open |\n"
    "| 3. At 10am | Is the 30-min range > 18 pts AND drift > 16 pts in reversal direction? | Enter signal |\n"
    "\n"
    "**What VIX tells you:** Higher VIX correlates with wider first-30-min ranges -- but it cannot predict whether the market will *reverse*. VIX is a volatility gauge, not a direction gauge. Use it to size your attention, not to skip the 10am confirmation.\n"
    "\n"
    "**The honest limit of pre-market prediction:** You cannot reliably know in advance if today will have a Strong drift reversal. The best you can do is eliminate low-probability calendar conditions and note elevated VIX. The actual edge is locked inside the 10am confirmation."
))

nb['cells'].extend(new_cells)

with open('analysis.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Done. Notebook now has {len(nb["cells"])} cells.')
